# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.


# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_public_key: <%= ENV['STRIPE_PUBLIC_KEY'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  GMAIL_USERNAME: <%= ENV['GMAIL_USERNAME'] %>


test:
  secret_key_base: dedc8c7225fb3700c96379b93a7c94ff29fa1a303630f476d9ea02976606099f40c01bad83b4d88659a714d8ddf35853754ac4fd2b30a32077ab89b10010ce63
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_public_key: <%= ENV['STRIPE_PUBLIC_KEY'] %>
  GMAIL_USERNAME: <%= ENV['GMAIL_USERNAME'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_public_key: <%= ENV['STRIPE_PUBLIC_KEY'] %>
  GMAIL_USERNAME: <%= ENV['GMAIL_USERNAME'] %>
  GMAIL_PASSWORD: <%= ENV['GMAIL_PASSWORD'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY']
